### ISSUE TITLE
localhost:9000 Stable Diffusion has stopped

### ISSUE THREAD

**Issue by jimqartworks** [cmdr2/stable-diffusion-ui#102]
TERMINAL error while running start.sh

./scripts/on_sd_start.sh: line 118: 7080 killed        
<img width="833" alt="Screen Shot 2022-09-07 at 8 45 26 AM" src="https://user-images.githubusercontent.com/112999421/188921806-c1ace786-b2b3-4dd7-9207-480f89f60eb4.png">
<img width="814" alt="Screen Shot 2022-09-07 at 8 45 08 AM" src="https://user-images.githubusercontent.com/112999421/188921811-6a32956e-e77f-4c6c-a946-42e4c04ad204.png">

**Comment by is0lated** [comment]
How much RAM do you have? I was running into OOM killer problems until I upgraded to 16GB of RAM.

**Comment by cmdr2** [comment]
Hi @jimqartworks The process will get killed if you're running out of RAM. It's unlikely to work well with 8 GB of RAM. If this is a VM, please try to increase the RAM to atleast 10-12 GB.

I'm closing this since there isn't much that can be done here, until Stable Diffusion releases less memory intensive models. Please feel free to re-open you do have more than 8 GB of RAM, and can't fix this even after you tried stopping everything on your PC.

Thanks!

**Comment by jimqartworks** [comment]
awesome, I have 16gb of Vram and only 5 GB of ram (via VirtualBox) I can increase the RAM, because my Mac has 16gb of RAM, again, I'm running it through UBUNTU via VirtualBox. THANKS,

**Comment by jimqartworks** [comment]
still having error, thanks for the help
<img width="871" alt="Screen Shot 2022-09-08 at 6 40 33 PM" src="https://user-images.githubusercontent.com/112999421/189254355-7c225b03-0d41-4e37-a57e-da4e1da0300c.png">

<img width="864" alt="Screen Shot 2022-09-08 at 6 37 53 PM" src="https://user-images.githubusercontent.com/112999421/189254292-f1e2f385-c9cf-47c5-b19d-35d3ed9458a1.png">

**Comment by cmdr2** [comment]
@jimqartworks Is that a different project that you're running? This isn't the klms-gui project :)

**Comment by cmdr2** [comment]
Please follow the steps described at https://github.com/cmdr2/stable-diffusion-ui#installation

**Comment by jimqartworks** [comment]
thanks for the response, yes its klms-gui
