### ISSUE TITLE
Suggestions:   large numbers in seed + much higher prompt textbox + scale up to 50 + Cancel-Button

### ISSUE THREAD

**Issue by AlphaRayReal** [cmdr2/stable-diffusion-ui#129]
-  seeds are only generated up to about 9999.  Had already identical seed numbers!   Other generates up to some millions!  This happens here extremly rarely. 
Actually i'm generating 30 picture.  The seed numbers of the last 21 are 80, 81, 82, [...] 99, 100, 101.   In that order (!!)   Randomization is not working correctly.

-  the prompt textbox ist too small.  My actual prompts have over 250 words and i have a lot to scroll.  And it's not only my problem.
The textbox should be about 3 up 4 times higher as actually

-  scale can be only set up to 20.  For some prompts i need values of 30 up 50 (like i used in other generator already used) which i can't set

- when generating higher number of images it should be possible to cancel the loop to change prompt

**Comment by uswin** [comment]
yep, random seed doesnt seem to work, it only increment the seed by 1, if possible, make two function,
1. random seed so each time the image use a very randomize seed from 0 to whatever the cap is, this will make the image look very randomize.

2. make an increment seed function just like now, so user just need to input starting seed number, and let the seed increment by 1 each time image generated thus making the image slightly different but still on the near starting seed.

thank you very much

**Comment by cmdr2** [comment]
Seeds are now upto 10 million. Update from 2 days ago.

@uswin The way seeds work, an image generated from `seed+1` will be totally different from an image from `seed`. It won't be just slightly different. Neighboring seeds don't mean they are "similar" to the previous seed.

This is how seeds in random number generation work, it's not specific to this project.

So if images are generated by incrementing the seed, they are still randomly different from each other, not just slightly. If they appear slightly different, it could be due to the prompt and settings.

**Comment by Seedmanc** [comment]
Prompt window is resizeable, I suggest making the negative prompt the same, as those tend to get sometimes as long as the positive ones.
