### ISSUE TITLE
A note regarding README BEFORE YOU RUN THIS.txt

### ISSUE THREAD

**Issue by XenoTheStrange** [cmdr2/stable-diffusion-ui#1320]
If you follow the installation instructions from [(https://github.com/cmdr2/stable-diffusion-ui#installation)] and install everything normally, inside of the "sd-ui-files" folder there's another file titled **"README BEFORE YOU RUN THIS.txt"** containing the line **"What you have downloaded is meant for the developers of this project, not for users."** ... But these files get downloaded during normal installation, so it's meant for users too... right?

It seems a bit misleading. Just a note.

**Comment by cmdr2** [comment]
Hi @XenoTheStrange I agree it's not ideal, but the reason for the file is because people sometimes download the entire git repository (instead of downloading the installers), and try to run the scripts - https://github.com/cmdr2/stable-diffusion-ui

That's why the file is present in the root of the repository - https://github.com/cmdr2/stable-diffusion-ui/blob/main/README%20BEFORE%20YOU%20RUN%20THIS.txt

sd-ui-files is a copy of the git repository that's used by the rest of the project. It's not intended to be seen or modified by users.
