### ISSUE TITLE
Option to disable auto-update on startup

### ISSUE THREAD

**Issue by dustinlacewell** [cmdr2/stable-diffusion-ui#183]
Currently, updates are performed automatically on startup. It'd be great if there was an option to disable this behavior.

**Comment by cmdr2** [comment]
Hi @dustinlacewell I understand where you're coming from. But this will be an option in the future. Right now the project is 22 days old, and all kinds of bugs are getting fixed every day. I do not have the resources to support all kinds of versions out there in the wild, as a single volunteer developer. As the project stabilizes, this will become an option.

There are two update channels: `beta` and `main`. People are on `main` by default, and that receives an update only once a feature has been on the `beta` channel for a while, and is working well. People can choose their channel by enabling/disabling the "Beta Channel" inside "Advanced Settings" on the UI.

As a side note, even though this project locks to a fixed version of Stable Diffusion, the Stable Diffusion codebase itself (which this project doesn't touch) has several places where it auto-downloads weights and configurations. And that's not in my control to stop, without custom patches to the Stable Diffusion code. Both two major outages of this project were caused by this, not by any update pushed by this project.

But I understand, and this will become an option as this project approaches a degree of stability. Until then, it won't be possible for me, as a single volunteer developer, to support all the versions in the wild. Thanks! :)

**Comment by dustinlacewell** [comment]
> Right now the project is 22 days old

Haha, I hear that. Great work and godspeed :)

**Comment by sbrow** [comment]
Let me preface my statement by saying that this project is a **godsend**. It has made installation and setup of stable-diffusion an absolute *breeze*. That being said...

I appreciate that this is a new project and that it's easier to manage if everyone is automagically on the latest version. However, for people that are using SDUI solely for the backend– when you push a breaking change that renames the endpoints and removes the ability to wait for a task to complete all the way before returning a response, it can be frustrating. Especially because there's no way to roll back.

Again, this project is amazing and I'm very grateful for the work that you have done. Just please be mindful that drastic changes like that could cause issues for your users in a way that is very hard to undo 🙂
