### ISSUE TITLE
start.sh only works if launched via "./start.sh" and not "sh start.sh"

### ISSUE THREAD

**Issue by NintendoManiac64** [cmdr2/stable-diffusion-ui#225]
**Describe the bug**
If you launch start.sh with `sh start.sh` then it will eventually fail after a minute or so despite `./start.sh` working without issue.

**To Reproduce**
1. Extract a fresh newly-downloaded copy of stable-diffusion-ui-linux.tar.xz (this step is ***crucial***)
2. Follow the readme steps for Linux
3. When it says to input `./start.sh` into the terminal, instead input `sh start.sh`
4. Press the 'Enter' key on your keyboard and wait a minute or so
5. Observe how it eventually throws up an error

**Expected behavior**
`sh start.sh` should behave identically to `./start.sh`

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 Xfce
 - Version: stable-diffusion-ui v2.05

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/11896003/191834085-ec899381-a8fc-4e4e-8b5e-e1eb8aeff0ca.png)

**Comment by cmdr2** [comment]
Hi, thanks for the report! This script is written assuming that bash is used.

It uses `#!/bin/bash` at the top, and like you said, that the instructions ask you to run it using `./start.sh` (and that works).

If you'd like to make it run with `sh start.sh` (which isn't a supported behavior), I'd be happy to accept a pull request / code contribution. Otherwise I won't be able to look into this right now, in favor of other priorities, given that the supported behavior is working fine.

Thanks!
