### ISSUE TITLE
UI Sugestion

### ISSUE THREAD

**Issue by DanielThorson** [cmdr2/stable-diffusion-ui#268]
Hi,

I'm a UX/UI Designer and I've been using your port of Stable Diffusion here and I love it!
I had some suggestions for a color scheme that I wanted to offer. I've attached some screenshots. I don't want this to sound like I'm trying to fix your design, its just another design that I thought you might like or want to incorporate. I would be happy to work with you on this.
In any case, thank you for your time and effort. Hope you have a great day!

Thank you,
Dan

![Screenshot 2022-09-29 12 13 14 PM](https://user-images.githubusercontent.com/81667518/193123032-aea2e9c2-4173-402f-bcd3-feff6dcb36ea.png)
![Screenshot 2022-09-29 12 13 48 PM](https://user-images.githubusercontent.com/81667518/193123070-05c3b850-457f-422d-9b65-10182547594e.png)
![Screenshot 2022-09-29 12 13 34 PM](https://user-images.githubusercontent.com/81667518/193123074-ecf25e32-5361-48ee-9cdc-5dfea1ba66e8.png)

**Comment by Hakorr** [comment]
I personally think this would be a downgrade regarding the colour scheme. The colours don't seem to compliment each other, the UI looks bland and too bright on certain parts.

**Comment by dumbstuffok** [comment]
IDK. Its not bad. Not a fan of the blue button, but I kinda like it.

**Comment by towcar** [comment]
I actually prefer the current design, but this does make me think changeable themes/skins/colours could be a solid feature. Then someone like @DanielThorson could submit a fresh design more openly.

**Comment by Polraudio** [comment]
Darker colors mess with my eyes more than bright colors so having the ability to have our own colors/themes/skins would be awesome.

**Comment by cmdr2** [comment]
Hi, thanks for the suggestion! Please drop by the #development channel on our discord (https://discord.com/invite/u9yhsFmEkB) if you'd like to discuss the UI changes. At the moment, I prefer the dark design since it's meant to be easier on the eyes.

But I understand that people may like themes, so that's why I'm inviting you to the discord channel to discuss this. Maybe you or a developer will find it interesting to implement the code changes for themes. I'd be happy to accept a pull-request for themes.

Thanks
