### ISSUE TITLE
Adding a "restart" button

### ISSUE THREAD

**Issue by jarble** [cmdr2/stable-diffusion-ui#273]
When Stable Diffusion fails to generate an image (sometimes due to a network error), I see a button to "remove" the image, but not to "restart" it.

Should we add "restart" buttons to the images so that they can be generated again when these errors happen?

**Comment by cmdr2** [comment]
Hi, the image failure (even if it says "network error") is never due to network errors. It would have printed the exact reason for the error in the black-and-white command prompt window, and usually it's due to memory constraints.

Running the same would probably cause the same error.

I will keep this in mind, and add this if more users ask for something like this. Thanks! :)
