### ISSUE TITLE
EULER_A as default sampler

### ISSUE THREAD

**Issue by maikelsz** [cmdr2/stable-diffusion-ui#282]
I've been looking at and testing examples, and it seems that the "euler_a" sampler produces the best initial results.
I think it would be advisable to use it as default instead of "plms"

**Comment by Polraudio** [comment]
Id have to agree on this one. Did multiple tests and it seems to get better results for me also.

**Comment by ChrisAcrobat** [comment]
I would like a mode where it use all of them, one at a time. Could be a like a comparable table, white sampler as column and seed+batch as row.
I think it very to much to just look at one sampler at a time.
Optionally multi select which samplers to use, if user would like to leave out some.

**Comment by maikelsz** [comment]
> 

I think is a little faster also, and get good results with less steps. need some more testing.

**Comment by cmdr2** [comment]
Hi, I'll keep this in mind, and I've for people's opinion at  https://discord.com/channels/1014774730907209781/1017058554290647062/1027931113261371424 and https://discord.com/channels/1014774730907209781/1014774732018683928/1027931307176640533

Let's continue the discussion there, since this is a subjective opinion, and I need a lot more voices to support this change. Thanks
