### ISSUE TITLE
Resuming prompts after closing and reopening the browser

### ISSUE THREAD

**Issue by jarble** [cmdr2/stable-diffusion-ui#285]
It seems that Stable Diffusion UI doesn't save the list of currently running prompts when I close and then reopen the browser window. Could the prompts and images be automatically saved and then resumed when the window is reopened?

**Comment by ChrisAcrobat** [comment]
Could be solved with use of [Window.localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) in [index.html](https://github.com/cmdr2/stable-diffusion-ui/blob/main/ui/index.html).

**Comment by jarble** [comment]
@ChrisAcrobat Window.localStorage has a limit of [only 10 megabytes](https://stackoverflow.com/a/2989317/975097), which might not be enough. Maybe [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) is a better option.

**Comment by ChrisAcrobat** [comment]
Agree!
_(Actually I ment IndexedDB. 😋)_

**Comment by cmdr2** [comment]
Hi, this is now possible. Please open System Settings (top-right corner) and press the "Configure" button next to "auto-save", and enable the checkbox next to "Prompts". This will now start auto-saving prompts across browser restarts.

Autosave isn't enabled for prompts by default, because that would be surprising for many users (especially given that we didn't do it previously). Thanks

**Comment by jarble** [comment]
@cmdr2  It seems that this setting saves the text in the input box, but it doesn't save the queue of prompts and generated images. Is there an option to save the queue as well?
