### ISSUE TITLE
'conda-unpack' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Wodienfor** [cmdr2/stable-diffusion-ui#333]
I wanted to installl this program, and I don't know how to install it properly.

I have Git running, but I'm not an expert at command prompts as it is a very hard thing to master. I might have done it wrong.

Any help is appreciated.
![image](https://user-images.githubusercontent.com/115841943/195953256-0b155e2f-a865-46c9-a616-14284123ad0e.png)

**Comment by cmdr2** [comment]
Hi, can you please try copying the `stable-diffusion-ui` folder inside the zip file and pasting that in `C:` ? Instead of extracting the zip file, please try copying the folder from inside it and pasting it.

A few people have reported a similar problem, and were able to solve it this way.

I've added this to the troubleshooting wiki: https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting#conda-unpack-is-not-recognized-as-an-internal-or-external-command

Please feel free to reopen this issue if the problem doesn't get fixed with this, thanks!
