### ISSUE TITLE
Adding metadata to output files

### ISSUE THREAD

**Issue by bach777** [cmdr2/stable-diffusion-ui#349]
Adding an option to save the metadata (prompts, settings used, etc) is essential. 

It would be great as it would improve the creative flow. 
Thanks in advance, I love the design of your ui!

**Comment by Grocel** [comment]
Maybe fill in UI from metadata too, when you input an image with appropriate metadata.

**Comment by JeLuF** [comment]
If you enable the auto-save feature in the system settings:

![image](https://user-images.githubusercontent.com/5852422/197890471-fcc47d97-4840-428d-bbd4-6955fe586bce.png)

a text file containing all the metadata is saved next to each image:
```
a photograph of an astronaut riding a horse
Width: 512
Height: 768
Seed: 3412
Steps: 25
Guidance Scale: 7.5
Prompt Strength: 0.8
Use Face Correction: None
Use Upscaling: None
Sampler: euler_a
Negative Prompt: 
Stable Diffusion Model: D:\stable-diffusion-ui\models\stable-diffusion\something.ckpt
```

For privacy reasons, the metadata is not saved to the picture, so that users can share pictures without sharing the prompt involuntarily.
