### ISSUE TITLE
Pip Subprocess Error: The Input Line is Too Long

### ISSUE THREAD

**Issue by bders** [cmdr2/stable-diffusion-ui#359]
Occurs during initial install
Installing pip dependencies: \ Ran pip subprocess with arguments:
['C:\\stable-diffusion-ui\\stable-diffusion\\env\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\stable-diffusion-ui\\stable-diffusion\\condaenv._hzop_oj.requirements.txt']
Pip subprocess output:

Pip subprocess error:
The input line is too long.
"C:\stable-diffusion-ui\stable-diffusion\tmp\tmpida8t3pl.bat" was unexpected at this time.

failed

CondaEnvException: Pip failed

**Expected behavior**
Install operates as normal

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Comment by cmdr2** [comment]
Hi @bders This error happens if you have an incorrect entry in your PATH environment variable. Most likely, you have %PATH% inside your PATH variable, which will result in a loop of increasingly long PATH entries.

That's something you'll need to fix in your system's environment variables, please check this using https://phoenixnap.com/kb/windows-set-environment-variable#ftoc-heading-4

Thanks!
