### ISSUE TITLE
Queue Management - Resume/Pause Support + Queue Reordering

### ISSUE THREAD

**Issue by Trithilon** [cmdr2/stable-diffusion-ui#373]
My workflow (many of my friends) involves rendering batches of hundreds of images overnight and then cherry picking some of them for variations or enhancement.
I love this UI because its almost like midjourney in its iteration workflow but enables you to do it at scale.
The only frustration is, sometimes you want your huge batches to pause, render a couple of images on priority and then resume its queue.

A simple concept would consist of 3 things:
1. A Global Pause All/Resume All button
2. Reordering Batches
3. Image batch level Force Start/Pause

### Quick Sample mockup:
![Stable Diffusion UI](https://user-images.githubusercontent.com/7444189/197346424-1f8a085b-36b1-4e00-8d22-ee77b90768c1.png)

This UI will make its queue management similar to that of torrent clients/download managers. But I feel it will hugely improve quality of life for people doing bulk rendering.

**Comment by JeLuF** [comment]
- Reordering has been implemented. You can grab a task and move it up and down in the queue. In Beta, a "grip" has been added, so that not the entire task but only the grip can be used to drag the task around.
- A pause feature has been added to beta. After pressing the pause button, the image currently being rendered will be finished, but no new images will be started. 
- Force start - I'd prefer not to implement this.
