### ISSUE TITLE
Error 803: system has unsupported display driver / cuda driver combination

### ISSUE THREAD

**Issue by hyperlogos** [cmdr2/stable-diffusion-ui#379]
**Describe the bug**
CUDA not working

**To Reproduce**
run start.sh
in the output see:
/home/drink/Software/stable-diffusion-ui/stable-diffusion/env/lib/python3.8/site-packages/torch/cuda/__init__.py:82: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755903507/work/c10/cuda/CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0
WARNING: No compatible GPU found. Using the CPU, but this will be very slow!

**Expected behavior**
GPU to be used since it supports CUDA. This is supposed to be a one-shot, right?

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Browser: Firefox 
 - Version: my branch is up to date with 'origin/main'.

**Comment by JeLuF** [comment]
Which GPU do you have?

**Comment by hyperlogos** [comment]
1070

**Comment by JeLuF** [comment]
The 1070 is supported, but requires quite recent drivers to work.
You can find the drivers at https://www.nvidia.com/en-gb/geforce/drivers/
Both the game ready and the studio ready driver should work.

**Comment by cmdr2** [comment]
Hi @hyperlogos The main error is `Error 803: system has unsupported display driver / cuda driver combination` - Please confirm that you have the latest drivers for Linux, and `nvidia-smi` shows the most recent CUDA compatibility (11.7).

`| NVIDIA-SMI 516.94       Driver Version: 516.94       CUDA Version: 11.7     |`

Otherwise there isn't much our UI can do here, if the driver/gpu combination doesn't work, sorry :/

Please feel free to reopen if this continues to be an issue after ensuring the latest driver is working. Thanks!
