### ISSUE TITLE
Better scheme for saving images to the disk

### ISSUE THREAD

**Issue by cmdr2** [cmdr2/stable-diffusion-ui#38]
There's a good PR for this #29, and the current approach saves by using the prompt for the folder name. The current scheme I've implemented isn't very good, because prompts change a lot during a single session, and it's annoying to split across different folders.

So #29 has a good suggestion, and there are some suggestions on Discord. Starting this issue to track the suggestions and arrive at a design that's better than the current one.

**Comment by search620** [comment]
Yes... so my suggestion is this

Because the name of the image and the folder cannot contain all the letters (in case the PROMPTS is too long)

My idea is this:
The file name of the image will be structured like this
Seed>prompts

The rest of the full details of the prompts, steps model, etc... will be saved in a separate file in a separate folder (which is in the same main folder as the images )

Now let's say I want to find the full details of a certain image, so now I'll copy the prompts name of the image  + seed (from the image) and look for the other details which already been created in the "prompt info dir"

**Comment by worthlesscog** [comment]
You could save them in a folder named by date so images generated on the same date are sat together. The current top level 8 digit hex isn't so useful if you're trying to find things you did yesterday or on Tuesday, for example. This would also put multiple sessions on the same date in the same place, whereas currently they'd end up in a different directories. I'm guessing currently it's some kind of session id.

Prompts can be too long or contain (OS specific) bad characters for a filename so putting the prompt and generation parameters in an accompanying text file is probably the best way. Following that you could just name the images and text files by generation time followed by the seed number. I'm guessing most folks would be browsing images by thumbnail anyway, so the filename isn't terrifically useful (as it's an incomplete prompt).

As a minor aside, that gives you the option of reloading the text file to regenerate from.

**Comment by cmdr2** [comment]
The format has stabilized since this issue was created. Additional control over the exact format is provided by the "File Format" UI plugin - https://github.com/ogmaresca/easydiffusion-plugins
