### ISSUE TITLE
for Windows This app won't work on your PC

### ISSUE THREAD

**Issue by 245463540** [cmdr2/stable-diffusion-ui#400]
拒绝访问。
"Packages to install: conda git"
拒绝访问。
"There was a problem while installing conda git using micromamba. Cannot continue."
请按任意键继续. . .

**Comment by Redhookz** [comment]
I had the exact same issue

**Comment by JeLuF** [comment]
Please check the folder `c:\stable-diffusion-ui\installer_files\mamba`. Is there a `micromamba.exe` file in there? What's the size of that file?

**Comment by unpera** [comment]
> 请检查文件夹。里面有文件吗？该文件的大小是多少？`c:\stable-diffusion-ui\installer_files\mamba``micromamba.exe`

its 0kb

**Comment by JeLuF** [comment]
Can you please delete `c:\stable-diffusion-ui`, unpack the installer again and retry the installation?

If this attempt creates any error messages, please do not retry the installation, but copy the error message and paste it here.

**Comment by cmdr2** [comment]
Thanks, fixed in https://github.com/cmdr2/stable-diffusion-ui/commit/873d4bd3f2017c0f17bd52f13310f8a804afce52

Please try deleting the folder and download the installer again from https://github.com/cmdr2/stable-diffusion-ui/releases/download/v2.3.5/stable-diffusion-ui-windows.zip

I've added a check to retry the download for micromamba, incase it is corrupt (or 0 bytes, like in this case).

Closing, please reopen if you continue facing this problem. Thanks!
