### ISSUE TITLE
Generated JPEGs have PNG as file extension

### ISSUE THREAD

**Issue by SkyeBlep** [cmdr2/stable-diffusion-ui#423]
**Describe the bug**
When I select output format jpeg, downloaded files are in jpeg format but with png file extension

**To Reproduce**
1. Set ouput format jpeg
2. Click make image
3. Hover over image and choose download
4. Filename is xxx.png, though format is actually jpg

**Impact**
This can make some external image programs not recognize the file until it is renamed with the correct .jpg extension

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser:  Firefox 105.0
 - Version: v2.3.5

**Comment by cmdr2** [comment]
Agreed, but I genuinely don't know how to fix this, because this is a bug in Firefox. We set the filename to include jpg, but firefox changes that.

We set the filename at: https://github.com/cmdr2/stable-diffusion-ui/blob/main/ui/media/js/main.js#L953 (which includes the correct extension)

And trigger the download at: https://github.com/cmdr2/stable-diffusion-ui/blob/main/ui/media/js/main.js#L330

Why Firefox insists on renaming it to png is beyond me.

**Comment by cmdr2** [comment]
Thanks, fixed in https://github.com/cmdr2/stable-diffusion-ui/commit/053bce7a8ee021650b71f4183c7a96e187cef4d1
