### ISSUE TITLE
"Draw Another 25 Steps" Does not behave as expected

### ISSUE THREAD

**Issue by Nutsandbolts800** [cmdr2/stable-diffusion-ui#429]
The drop down button "Draw Another 25 Steps" Appears to instead, run the same initial number of steps again, instead of running 25 more steps. If the initial interference steps was set to 200, the button appears to draw another 200 steps, not another 25. 

**To Reproduce**
1. make an image with 500 steps
2. once complete, select "Draw another 25 steps"
3. observe error "index 1000 is out of bounds for dimension 0 with size 1000" indicating the sw is attempting to draw another 500 steps, not another 25

**Expected behavior**
either the sw should continue to iterate 25 more steps when the button is pressed OR the sw should change the button from saying "draw 25 more steps" to "Draw (x) more steps" with x being the initial interference steps

**Desktop (please complete the following information):**
 - OS: Win 10 21H2
 - Browser: Chrome 106.0.5249.121
 - Version: v2.3.5

**Additional context**

**Comment by JeLuF** [comment]
The "Draw another 25 steps" re-runs the rendering job with another 25 steps added to it. So clicking "Draw another 25 steps" on a 500 step image, it would render a new image with 525 steps.

Due to limitations in the stable diffusion version used by the project, img2img can only be used with the ddim sampler. Due to this, we can't use img2img to just take the image and run another 25 steps, but the software has to rerender the first 500 steps and then another 25 steps. 

You can see this step count in the job description:
![image](https://user-images.githubusercontent.com/5852422/199129239-d054f543-5d1e-4ab9-8d8a-d450eb8b2deb.png)

**Comment by cmdr2** [comment]
@Nutsandbolts800  This error `index 1000 is out of bounds for dimension 0 with size 1000` indicates that your `guidance scale` was probably set too low (less than 5).

I just tested it on v2.3.5 and it works okay - "Draw another 25" on 200 steps results in 225 steps.

![image](https://user-images.githubusercontent.com/844287/199393168-f8953ce9-b3b6-4c52-8543-fa56b20c3d32.png)
![image](https://user-images.githubusercontent.com/844287/199393185-13ad8d91-c210-419e-985d-f2985393d2cf.png)

Please feel free to re-open if this continues to be an issue (with the exact settings used for the error). Thanks!
