### ISSUE TITLE
Problem installing conda git?

### ISSUE THREAD

**Issue by MikeS210** [cmdr2/stable-diffusion-ui#433]
After unzipping and moving the file to F:/ drive, I get the following message after double clicking Start Stable Diffusion UI.cmd:

![image](https://user-images.githubusercontent.com/117284397/199497661-880b18b8-b9ca-40d7-93f7-150add4187bd.png)

If I right click Start Stable Diffusion UI.cmd and run as admin I get this message:

![image](https://user-images.githubusercontent.com/117284397/199498286-dc594769-7688-4e94-8a22-7af6421e89b2.png)

**Comment by cmdr2** [comment]
Please delete and extract the folder again from the zip, since you shouldn't run it as admin. :)

Regarding the first error, can you please try these steps:
1. Run `Start Stable Diffusion UI.cmd` again, and it's okay if it fails
2. Manually download https://github.com/cmdr2/stable-diffusion-ui/releases/download/v1.1/micromamba.exe and put it inside the `stable-diffusion-ui\installer_files\mamba` folder, replacing the existing `micromamba.exe` file.
3. Run `Start Stable Diffusion UI.cmd` again

Let's see if that works.

**Comment by MikeS210** [comment]
That worked. Thank you

**Comment by EisenCrab** [comment]
Hi, I have a similar problem, but it looks a little different. Replacing micromamba.exe didn't work.
![image](https://user-images.githubusercontent.com/117412637/199853799-90b6849e-b545-403a-a2d8-20234a2dd7e6.png)
When I click "continue" the error description is the same
![image](https://user-images.githubusercontent.com/117412637/199854102-992d7b19-e73e-499c-a620-f91ff001a6d7.png)

**Comment by JeLuF** [comment]
@EisenCrab, your error is a different one. Micromamba is silently failing in some situations. You can use our alternative installer:
https://github.com/cmdr2/stable-diffusion-ui/releases/download/v2.16/stable-diffusion-ui-win64.zip
Please delete the `D:\stable-diffusion-ui` folder before extracting this installer.

**Comment by cmdr2** [comment]
@EisenCrab The suggestion that @JeLuF gave you should fix the problem.

But can you also please run these steps:
1. Press Win+R, type "cmd" and press Run
2. Type `echo %TEMP%` and press enter
3. Type `echo %TMP%` and press enter
4. Type `echo %USERPROFILE%` and press enter

Can you please copy and paste the output of those commands here? Thanks
