### ISSUE TITLE
Please add support for AMD Radeon GPUs on OS Windows

### ISSUE THREAD

**Issue by andrio1988** [cmdr2/stable-diffusion-ui#659]
I am very frustrated that there is no support for AMD graphics cards on Windows and I really want this support to appear.

All the more, if I understand correctly, there are ways and possibilities to do so.

https://github.com/harishanand95/diffusers/tree/dml
and
https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/PyPI/ort-nightly-directml/overview/1.13.0.dev20220908001

**Comment by BlackWarriorNT** [comment]
yes, add amd support, please

**Comment by jaemil** [comment]
Would also love to see windows with amd support

**Comment by jamiecropley** [comment]
I would love to contribute on getting AMD GPU's working with this.

So far here are all the threads on AMD GPU's:
https://github.com/cmdr2/stable-diffusion-ui/issues/579
https://github.com/cmdr2/stable-diffusion-ui/issues/499
https://github.com/cmdr2/stable-diffusion-ui/issues/176
https://github.com/cmdr2/stable-diffusion-ui/issues/138
https://github.com/cmdr2/stable-diffusion-ui/issues/115

Theres constantly raised issues around AMD GPU's, instead of asking for support for something it is obviously does not support, I ask to yourselves, how can I contribute and get this running on here then submit it to the actual code for others?

**Comment by Toaster143** [comment]
Please AMD support. It would be so cool if it was that easy to put jobs on different devices maybe on the same time. 
BTW:
Does anyone know how to make local changes?
Because it's a bit tricky that there is always an automatic update each start.

**Comment by jamiecropley** [comment]
See above, honestly, at this point theres more people asking for it than working on it. It's better to offer support I reckon to actually amend the code.

**Comment by JeLuF** [comment]
>BTW: Does anyone know how to make local changes? Because it's a bit tricky that there is always an automatic update each start.

Check out this guide in the documentation: https://github.com/cmdr2/stable-diffusion-ui/blob/main/CONTRIBUTING.md

**Comment by jamiecropley** [comment]
> > BTW: Does anyone know how to make local changes? Because it's a bit tricky that there is always an automatic update each start.
> 
> Check out this guide in the documentation: https://github.com/cmdr2/stable-diffusion-ui/blob/main/CONTRIBUTING.md

Thanks!!! I was getting round to looking for that lol.

I dunno of the relevance, but I also found this recently which apparently supports AMD GPU's https://github.com/nod-ai/SHARK

**Comment by cmdr2** [comment]
Tracking this in https://github.com/cmdr2/stable-diffusion-ui/issues/115

Current status: AMD now works out-of-the-box on Linux, but not yet on Windows
