### ISSUE TITLE
Compatibility with NVIDIA GTX 960M

### ISSUE THREAD

**Issue by aevfly** [cmdr2/stable-diffusion-ui#743]
Hi,
I have two GPU on my laptop, one of them is GTX 960M , I know that is not very fast and not very slow (among contemporary GPU) 
This GPU should more fast as using CPU. 
I can't change parameters using GPU on setting, and could be better if available use both GPU. 

This is a request for compatibility with NVIDIA GTX 960M
Thx 

 - OS: Win 10 x64 
 - Browser: Firefox 
 - Version: 108.0.1

**Comment by TheRealGordonRamsay** [comment]
im having a similar issue, decided not to open a new bug report because this seems to be very similar.
I have a RTX 3080 desktop gpu with 10gb vram..
nvidia is running GeForce driver 528.02 and CUDA toolkit 12.x

I did fresh install and did the default "photograph of astronaut riding a horse" prompt and let it run for about 10 minutes, and neither cpu nor gpu really seem to be doing anything at all.

It does show cuda:0 as an active device, but lower in the logs it shows cpu for `model.device` and `modelFS.device` 

![Pic showing the idling resources while running inference](https://user-images.githubusercontent.com/83257460/211214452-4f777f71-6b6a-4add-9ea1-1e257cf3287a.png)
[logs.txt](https://github.com/cmdr2/stable-diffusion-ui/files/10369276/logs.txt)

**Comment by EricLam554** [comment]
I had the same issue before and fixed it by updating the Nvidia driver

**Comment by xjdeng** [comment]
I have a 960M with 4GB on am older laptop. It works with the -medvram setting and 512x512 images seem to take about 1 minute to generate using PyTorch 2. Xformers doesn't seem to help much and seems to even slow things down in some cases.

**Comment by aevfly** [comment]
yes, it works even on my 960M with 2GB, 
I also add args  --lowvram

**Comment by blahole** [comment]
> yes, it works even on my 960M with 2GB, I also add args --lowvram

where is the position of adding args? which file?

**Comment by aevfly** [comment]
> > yes, it works even on my 960M with 2GB, I also add args --lowvram
> 
> where is the position of adding args? which file?

in webui-user.bat 
add this: 

set GIT=
set VENV_DIR=
**set COMMANDLINE_ARGS=--xformers --lowvram --opt-split-attention**

call webui.bat

**Comment by blahole** [comment]
> > > yes, it works even on my 960M with 2GB, I also add args --lowvram
> > 
> > 
> > where is the position of adding args? which file?
> 
> in webui-user.bat add this:
> 
> set GIT= set VENV_DIR= **set COMMANDLINE_ARGS=--xformers --lowvram --opt-split-attention**
> 
> call webui.bat

What I wish to know is in the easydiffusion project. After "pip install xformers", is OK?

**Comment by JeLuF** [comment]
EasyDiffusion does not have command line arguments. `webui-user.bat` is a file from Automatic1111's StableDiffusion distribution and has nothing to do with EasyDiffusion.
