### ISSUE TITLE
Please make a version with Terminal UI for us headless people

### ISSUE THREAD

**Issue by bitcoinmeetups** [cmdr2/stable-diffusion-ui#8]
Please make a version with Terminal UI instead of browser for us headless people

**Comment by cmdr2** [comment]
Hi, you can use `cog` to use this docker image directly from the terminal. The browser UI is built around the same docker image.

Please check "Run on your own computer" on https://replicate.com/stability-ai/stable-diffusion

For e.g. `cog predict r8.im/stability-ai/stable-diffusion@sha256:3080f37ef32771c9984d65033cbe71caa96c69680008bae64cf691724a6df04c -i prompt="photo of an astronaut riding a horse"`

Closing this issue since cog is essentially a terminal version of this tool. Building a graphical TUI (Terminal UI) is not within the scope of this project unfortunately.

Thanks!
