### ISSUE TITLE
GPU gt1030 not supported

### ISSUE THREAD

**Issue by DDru** [cmdr2/stable-diffusion-ui#891]
Describe the bug:
GPU gt1030 not supported. Yes it's fun because card too old, but for example i can use Cuda in Blender 3 Cycles render.
Can you add support?

Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by JeLuF** [comment]
As far as I can tell, the GT1030 has only 2GB of memory. Easy Diffusion (or rather its sister project sdkit) includes a lot of optimizations so that Easy Diffusion can be run with only 3-4 GB of Video RAM. The origintal Stable Diffusion code needs something like 10GB to run. But 2GB is just not enough.
