### ISSUE TITLE
Python enviroment Linux Mint

### ISSUE THREAD

**Issue by agentsimon** [cmdr2/stable-diffusion-ui#979]
**Is your feature request related to a problem? Please describe.**
My installation on Mint 22 never uses Xformers. The conda enviroment uses Python 3.8.5 and I cannot discover the conda env name,conda list only reveals Base
**Describe the solution you'd like**
![screenshot](https://user-images.githubusercontent.com/31639346/223844910-62a66388-8f8b-43ac-bde9-c92309569e1b.png)
![screenshot2](https://user-images.githubusercontent.com/31639346/223844921-69a8a62b-1a9b-4540-8245-24a106f7ae7a.png)

How can I install Xformers for my installation

**Describe alternatives you've considered**
I have tried running it in the Base enviroment but to no avail

**Additional context**
![screenshot2](https://user-images.githubusercontent.com/31639346/223845022-8c3d1f33-441c-45fb-ad78-d44ab1f4f4c2.png)

**Comment by glitchstroke** [comment]
Short Answer - instead of starting up stable-diffusion-ui as normal with `./start.sh` run `./developer_console.sh` and you can just `pip install xformers` from there. I imagine you should be able to upgrade python from within there as well, but I managed to unexpectedly delete that conda environment while trying something else, and when it reinstalled, it reinstalled itself with python 3.10.4

Long answer seems irrelevant at this point, but if that doesn't fix it for you, let me know

**Comment by agentsimon** [comment]
Yes, that did the job perfectly. I had to install triton as well as xformers . For some reason the first pip install didn't work but after a repeat install it worked. 

So the whole process was use the Beta version, start it with the developer sh script and install xformers and triton from the command line using pip. After doing that using the start sh script with the Beta version is fine.

**Comment by cmdr2** [comment]
The wiki also mentions this now - https://github.com/cmdr2/stable-diffusion-ui/wiki/xFormers
